parameters:
- name: PoolType
  type: string
  values:
    - 'VM'
    - 'Pool'
  
- name: PoolName
  type: string

- name: LocalVariables
  type: string


stages:
- stage: Build
  displayName: 'CI Build'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  dependsOn: []

  jobs:
  - job: BuildAndPackage
    displayName: 'Build, Test, and Package'
    
    variables:
    - template: '${{ parameters.LocalVariables }}@self'
    - template: '../variables/versions.yml'
    
    pool:
      ${{ if eq( parameters.PoolType, 'VM' )}}:
        vmImage: ${{ parameters.PoolName }}
      ${{ if eq( parameters.PoolType, 'Pool' )}}:
        name: ${{ parameters.PoolName }}
    
    steps:
    - checkout: self
      submodules: true

    - task: Assembly-Info-NetCore@2
      displayName: 'Set Assembly Info'
      inputs:
        Path: '$(Build.SourcesDirectory)'
        FileNames: '${{ variables.TargetProject }}'
        InsertAttributes: true
        FileEncoding: 'auto'
        WriteBOM: false
        PackageRequireLicenseAcceptance: true
        PackageId: '${{ variables.PackageId }}'
        Authors: '${{ variables.Authors }}'
        Company: '${{ variables.Company }}'
        Product: '${{ variables.Product }}'
        PackageLicenseUrl: '${{ variables.LicenseUrl }}'
        RepositoryUrl: 'https://github.com/${{ variables.RepoName }}'
        PackageIconUrl: '${{ variables.IconUrl }}'
        RepositoryType: '${{ variables.RepoType }}'
        VersionNumber: '$(SemanticVersion).$(Build.BuildId)'
        FileVersionNumber: '$(SemanticVersion).$(Build.BuildId)'
        InformationalVersion: '$(SemanticVersion)'
        PackageVersion: '$(SemanticVersion)'
        LogLevel: 'verbose'
        FailOnWarning: false
        DisableTelemetry: false

    - template: '../steps/restore-build-test.yml'
    
    - template: '../steps/package-artifacts.yml'
      parameters: 
        PackageToPack: ${{ variables.TargetProject }}
        OutputDir: 'Alpha'
        VersionVariable: 'AlphaVersion'

    - template: '../steps/package-artifacts.yml'
      parameters: 
        PackageToPack: ${{ variables.TargetProject }}
        OutputDir: 'Beta'
        VersionVariable: 'BetaVersion'

    - template: '../steps/package-artifacts.yml'
      parameters: 
        PackageToPack: ${{ variables.TargetProject }}
        OutputDir: 'Release'
        VersionVariable: 'SemanticVersion'

