parameters:
- name: PoolType
  type: string
  values:
    - 'VM'
    - 'Pool'
  
- name: PoolName
  type: string

- name: LocalVariables
  type: string


stages:
- stage: PullRequest
  displayName: 'PR Build Check'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  dependsOn: []

  jobs:
  - job: BuildAndTest
    displayName: 'Build and Run Unit Tests'
    
    variables:
    - template: '${{ parameters.LocalVariables }}@self'
    
    pool:
      ${{ if eq( parameters.PoolType, 'VM' )}}:
        vmImage: ${{ parameters.PoolName }}
      ${{ if eq( parameters.PoolType, 'Pool' )}}:
        name: ${{ parameters.PoolName }}
    
    steps:
    - checkout: self
      submodules: true

    - template: '../steps/restore-build-test.yml'

    